#!/usr/bin/env bash

YEAR=$1
DAY=$2
PART=${3:-1}

if [[ $DAY -lt 10 ]]; then
  DIR=day0$1
else
  DIR=day$1
fi

cd ~/aoc/$YEAR/$DIR

set -o pipefail
while true; do
cat puzzle.html \
  | pup -p -i 0 --pre article \
  | html-minifier --collapse-whitespace \
  | pandoc --from=html --to=markdown_strict+backtick_code_blocks --lua-filter=../../misc/code_block.lua --wrap=none \
  | sed 's/` \([.,:;!?)]\)/`\1/g' \
  | sed 's/\([(]\) `/\1`/g' \
  | sed 's/* \([.,:;!?)]\)/*\1/g' \
  | sed 's/\([(]\) \*/\1*/g' \
  | glow -p -s ../../misc/glow.json \
  || exit
done
